name: Deploy to Amplify

on:
  workflow_dispatch:
  push:
    branches: [develop, qa, main]

  pull_request:
    branches: [develop, qa, main]
      
permissions:
  id-token: write 
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'main' || github.ref_name == 'qa' && 'qa' || 'develop' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Adjust environment based on branch
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "ENV=main" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "qa" ]]; then
            echo "ENV=qa" >> $GITHUB_ENV
          else
            echo "ENV=develop" >> $GITHUB_ENV
          fi

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHubActions
          role-duration-seconds: 3600

      - name: Install Amplify CLI
        run: npm install -g @aws-amplify/cli

      - name: Configure Amplify
        run: amplify configure  

      - name: Deploy to Amplify
        run: amplify publish